# Generated by Django 4.0.2 on 2022-05-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='DiaDanh',
        ),
    ]
