# Generated by Django 4.0.2 on 2022-05-04 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_rename_category_diadanh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('image', models.ImageField(default=None, upload_to='tour/%Y/%m')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('diadanh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.diadanh')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('subject', 'diadanh')},
            },
        ),
    ]
