# Generated by Django 4.0.2 on 2022-05-05 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tintuc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintuc',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tintucs', to='tour.tour'),
        ),
    ]
