# Generated by Django 4.0.2 on 2022-05-11 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_tintucview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintucview',
            name='tintuc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tour.tintuc'),
        ),
    ]
