# Generated by Django 4.0.2 on 2022-05-18 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_alter_tintucview_tintuc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tintuc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tintuc'),
        ),
    ]
